spring.application.name=chatbot

spring.datasource.url=${DATABASE_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

huggingface.api-key=${HF_API_KEY}
huggingface.model=${MODEL}
huggingface.url=${BASE_URL}

spring.security.jwt.secret=${JWT_SECRET}
server.port=8080
